version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-base-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
