#!/usr/bin/env bash

NAME="vsl"
VERSION=${VERSION:-"latest"}

echo
echo
echo "... docker .................................................."
echo "............................................................."
echo

echo "Building ulisesjeremias/$NAME:$VERSION"

docker build --no-cache -t ulisesjeremias/$NAME:"$VERSION" . --build-arg VSL_VERSION="$VERSION"
docker images -q -f "dangling=true" | xargs docker rmi
