name: Deploy Documentation

env:
  VJOBS: '2'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VSL
        uses: actions/checkout@v7
        with:
          path: vsl

      - name: Setup V
        uses: vlang/setup-v@v1.7
        with:
          check-latest: true

      - name: Copy VSL to V Modules
        run: |
          mkdir -p ~/.vmodules
          cp -a ./vsl ~/.vmodules/vsl

      - name: V doctor
        env:
          VJOBS: '2'
        run: |
          cd ~/.vmodules
          env HOME="$HOME" PATH="$PATH" VJOBS=2 v doctor

      - name: Build docs
        run: |
          cd ~/.vmodules/vsl
          rm -rf examples
          rm -f README.md
          mv static/DOCS.md README.md
          cd ~/.vmodules
          env HOME="$HOME" PATH="$PATH" VJOBS=2 \
            v doc -readme -m -f html ./vsl

      - name: Stage generated docs
        run: |
          mkdir -p ./vsl/_docs
          cp -a ~/.vmodules/vsl/_docs/. ./vsl/_docs/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vsl/_docs/
