name: Validate Docs

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout VSL
      uses: actions/checkout@v2
      with:
        path: vsl
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Move VSL source code to V Modules
      run: mv ./vsl ~/.vmodules
    - name: Validate docs
      run: |
        cd ~/.vmodules/vsl
        v check-md .
