name: Todo Checker

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
        id: todo
